# Copyright Â© SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: MIT

[package]
name = "pinch-to-zoom"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]

[[bin]]
name = "pinch-to-zoom"
path = "main.rs"

[dependencies]
slint = { path = "../../api/rs/slint" }
