# Copyright Â© SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: MIT

# This example is not part of the Slint Cargo workspace because of the git dependency to bevy. Once bevy
# releases a version to crates.io that depends on WGPU 26, we can re-insert the example into the workspace.
[workspace]

[package]
name = "bevy-example"
version = "1.14.0"
authors = ["Slint Developers <info@slint.dev>"]
edition = "2021"
publish = false
license = "MIT"
description = "Slint Bevy Integration Example"

[[bin]]
name = "bevy_example"
path = "main.rs"

[dependencies]
slint = { path = "../../api/rs/slint", features = ["unstable-wgpu-26", "renderer-skia"] }
spin_on = { version = "0.1" }
bevy = { version = "0.17.0-rc.1", default-features = false, features = ["bevy_core_pipeline", "bevy_pbr", "bevy_window", "bevy_scene", "bevy_gltf", "bevy_log", "jpeg", "png", "tonemapping_luts", "multi_threaded", "reflect_auto_register", "debug"] }
bevy_image = { version = "0.17.0-rc.1", features = ["zstd_rust"] }
smol = { version = "2.0.0" }
async-compat = { version = "0.2.4" }
reqwest = { version = "0.12", features = ["stream"] }
