# Copyright Â© SixtyFPS GmbH <info@slint-ui.com>
# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-1.0 OR LicenseRef-Slint-commercial

[package]
name = "slint-updater"
version = "1.1.0"
authors = ["Slint Developers <info@slint-ui.com>"]
edition = "2021"
license = "GPL-3.0-only OR LicenseRef-Slint-Royalty-free-1.0 OR LicenseRef-Slint-commercial"
description = "Tool used to update .slint files from previous versions"
repository = "https://github.com/slint-ui/slint"
homepage = "https://slint-ui.com"


[dependencies]
i-slint-compiler = { version = "=1.1.0", path = "../../internal/compiler", features = ["display-diagnostics"] }

clap = { version = "4.0", features = ["derive", "wrap_help"] }
codemap = "0.1"
codemap-diagnostic = "0.1.1"
spin_on = "0.1"
by_address = "1.0.4"

[[bin]]
name = "slint-updater"
path = "main.rs"
