# Copyright Â© 2025 David Haig
# SPDX-License-Identifier: MIT

[package]
name = "slint-generated"
version = "1.12.1"
edition = "2021"
build = "build.rs"
authors = ["David Haig <david@ninjametal.com>"]
readme = "README.md"
resolver = "2"
license = "MIT"
publish = false
repository = "https://github.com/slint-ui/slint"
homepage = "https://slint.dev"

[dependencies]
slint = { path = "../../../api/rs/slint", default-features = false, features = ["compat-1-2", "unsafe-single-threaded", "libm", "renderer-software"] }
i-slint-core-macros = { path = "../../../internal/core-macros" }

[build-dependencies]
slint-build = { path = "../../../api/rs/build" }

#[dependencies]
#slint = { version = "1.9.1", default-features = false, features = [
#    "compat-1-2",
#    "unsafe-single-threaded",
#    "libm",
#    "renderer-software",
#] }
#i-slint-core-macros = { version = "1.9.1" }
#
#[build-dependencies]
#slint-build = { version = "1.9.1" }
