[package]
name = "sixtyfps-macros"
version = "0.0.2"
authors = ["SixtyFPS <info@sixtyfps.io>"]
edition = "2018"
license = "GPL-3.0-only"
description = "Macro helper for sixtyfps crate"
repository = "https://github.com/sixtyfpsui/sixtyfps"
homepage = "https://sixtyfps.io"


[lib]
proc-macro = true
path = "lib.rs"

[dependencies]
quote = "1.0"
proc-macro2 = "1.0.17"
sixtyfps-compilerlib = { version = "=0.0.2", path = "../../../sixtyfps_compiler", features = ["proc_macro_span", "rust"] }

