# Copyright Â© SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-1.0 OR LicenseRef-Slint-commercial

[package]
name = "i-slint-backend-selector"
version = "1.1.1"
authors = ["Slint Developers <info@slint.dev>"]
edition = "2021"
license = "GPL-3.0-only OR LicenseRef-Slint-Royalty-free-1.0 OR LicenseRef-Slint-commercial"
description = "Helper crate to pick the default rendering backend for Slint"
repository = "https://github.com/slint-ui/slint"
homepage = "https://slint.dev"

[lib]
path = "lib.rs"

[features]
backend-winit = ["backend-winit-x11", "backend-winit-wayland"]
backend-winit-x11 = ["i-slint-backend-winit/x11"]
backend-winit-wayland = ["i-slint-backend-winit/wayland"]

renderer-winit-femtovg = ["i-slint-backend-winit/renderer-winit-femtovg"]
renderer-winit-skia = ["i-slint-backend-winit/renderer-winit-skia"]
renderer-winit-skia-opengl = ["i-slint-backend-winit/renderer-winit-skia-opengl"]
renderer-winit-skia-vulkan = ["i-slint-backend-winit/renderer-winit-skia-vulkan"]
renderer-winit-software = ["i-slint-backend-winit/renderer-winit-software"]

rtti = ["i-slint-core/rtti", "i-slint-backend-qt?/rtti"]
accessibility = ["i-slint-backend-winit?/accessibility"]

[dependencies]
i-slint-core = { version = "=1.1.1", path = "../../../internal/core", default-features = false }
i-slint-backend-winit = { version = "=1.1.1", path = "../winit", optional = true }
i-slint-backend-qt = { version = "=1.1.1", path = "../qt", optional = true }

cfg-if = "1"
