# Copyright Â© SixtyFPS GmbH <info@sixtyfps.io>
# SPDX-License-Identifier: (GPL-3.0-only OR LicenseRef-SixtyFPS-commercial)

[package]
name = "sixtyfps-rendering-backend-selector"
version = "0.2.0"
authors = ["SixtyFPS <info@sixtyfps.io>"]
edition = "2021"
license = "(GPL-3.0-only OR LicenseRef-SixtyFPS-commercial)"
description = "Helper crate to pick the default rendering backend for SixtyFPS"
repository = "https://github.com/sixtyfpsui/sixtyfps"
homepage = "https://sixtyfps.io"

[lib]
path = "lib.rs"

[features]
wayland = ["sixtyfps-rendering-backend-gl/wayland"]
x11 = ["sixtyfps-rendering-backend-gl/x11"]

[dependencies]
slint-core-internal = { version = "=0.2.0", path = "../../../internal/core", default-features = false }
sixtyfps-rendering-backend-gl = { version = "=0.2.0", path = "../gl", optional = true }
slint-backend-qt-internal = { version = "=0.2.0", path = "../qt", optional = true }

cfg-if = "1"
