# Copyright Â© SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-1.1 OR LicenseRef-Slint-commercial

[package]
name = "i-slint-backend-selector"
description = "Helper crate to pick the default rendering backend for Slint"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
path = "lib.rs"

[features]
backend-winit = ["backend-winit-x11", "backend-winit-wayland"]
backend-winit-x11 = ["i-slint-backend-winit/x11"]
backend-winit-wayland = ["i-slint-backend-winit/wayland"]
backend-linuxkms = ["i-slint-backend-linuxkms"]

renderer-femtovg = ["i-slint-backend-winit?/renderer-femtovg", "i-slint-backend-linuxkms?/renderer-femtovg"]
renderer-skia = ["i-slint-backend-winit?/renderer-skia", "i-slint-backend-linuxkms?/renderer-skia"]
renderer-skia-opengl = ["i-slint-backend-winit?/renderer-skia-opengl", "i-slint-backend-linuxkms?/renderer-skia-opengl", "i-slint-renderer-skia/opengl"]
renderer-skia-vulkan = ["i-slint-backend-winit?/renderer-skia-vulkan", "i-slint-backend-linuxkms?/renderer-skia-vulkan", "i-slint-renderer-skia/vulkan"]
renderer-software = ["i-slint-backend-winit?/renderer-software", "i-slint-core/software-renderer"]

rtti = ["i-slint-core/rtti", "i-slint-backend-qt?/rtti"]
accessibility = ["i-slint-backend-winit?/accessibility"]

default = []

[dependencies]
i-slint-core = { workspace = true }
i-slint-backend-winit = { workspace = true, features = ["default"], optional = true }
i-slint-backend-qt = { workspace = true, features = ["default"], optional = true }
i-slint-backend-linuxkms = { workspace = true, features = ["default"], optional = true }
i-slint-renderer-skia = { workspace = true, optional = true }

cfg-if = "1"

[build-dependencies]
i-slint-common = { workspace = true }
