# Copyright Â© SixtyFPS GmbH <info@sixtyfps.io>
# SPDX-License-Identifier: (GPL-3.0-only OR LicenseRef-SixtyFPS-commercial)

[package]
name = "parser_test_macro"
version = "0.2.0"
authors = ["SixtyFPS <info@sixtyfps.io>"]
edition = "2021"
publish = false
license = "(GPL-3.0-only OR LicenseRef-SixtyFPS-commercial)"

[lib]
proc-macro = true
path = "lib.rs"

[dependencies]
quote = "1.0"
