# Copyright Â© SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: MIT

[workspace]
members = ["crate", "examples/gallery", "tests/doctests"]
default-members = ["crate", "examples/gallery", "tests/doctests"]
resolver = "3"

[workspace.package]
rust-version = "1.85"
authors = ["Slint Developers <info@slint.dev>"]
version = "0.1.0"
license = "MIT"
homepage = "https://material.slint.dev"
edition = "2021"
documentation = "https://material.slint.dev"
repository = "https://github.com/slint-ui/material-components"
