# Copyright Â© Luke. D Jones <luke@ljones.dev>
# SPDX-License-Identifier: MIT

[package]
name = "zed_slint"
version = "1.16.0"
edition.workspace = true
publish = false
license = "MIT"

[dependencies]
zed_extension_api = "0.6.0"

[lib]
path = "src/slint.rs"
crate-type = ["cdylib"]
