# Copyright Â© Luke. D Jones <luke@ljones.dev>
# SPDX-License-Identifier: MIT

id = "slint"
name = "Slint"
description = "Slint support for Zed"
version = "1.16.0"
schema_version = 1
authors = ["Slint Developers <info@slint.dev>", "Luke. D Jones <luke@ljones.dev>"]
repository = "https://github.com/slint-ui/slint"

[language_servers.slint]
name = "Slint LSP"
language = "Slint"

[grammars.slint]
repository = "https://github.com/slint-ui/tree-sitter-slint.git"
commit = "5dafe6745dd3bb24342acebe478015b642dc7135"
