# Copyright Â© SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-1.0 OR LicenseRef-Slint-commercial

[package]
name = "slint-tr-extractor"
version = "1.1.0"
authors = ["Slint Developers <info@slint.dev>"]
edition = "2021"
license = "GPL-3.0-only OR LicenseRef-Slint-Royalty-free-1.0 OR LicenseRef-Slint-commercial"
description = "Tool used to update extract @tr string out of Slint files into gettext .po file"
repository = "https://github.com/slint-ui/slint"
homepage = "https://slint.dev"

[dependencies]
i-slint-compiler = { version="=1.1.0", path = "../../internal/compiler", features = ["display-diagnostics"] }
chrono = {version = "0.4.24", default-features = false, features = ["clock"] }
clap = { version = "4.0", features = ["derive", "wrap_help"] }
polib = "0.2"

[dev-dependencies]
itertools = "0.11"

[[bin]]
name = "slint-tr-extractor"
path = "main.rs"
