# Copyright Â© SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Community OR LicenseRef-Slint-commercial

[package]
name = "slint-tr-extractor"
description = "Tool used to update extract @tr string out of Slint files into gettext .po file"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true
categories = [ "gui", "command-line-utilities", "development-tools" ]

[dependencies]
i-slint-compiler = { workspace = true, features = ["default", "display-diagnostics"] }
chrono = {version = "0.4.24", default-features = false, features = ["clock"] }
clap = { version = "4.0", features = ["derive", "wrap_help"] }
polib = "0.2"

[dev-dependencies]
itertools = { workspace = true }

[[bin]]
name = "slint-tr-extractor"
path = "main.rs"
