# Copyright Â© SixtyFPS GmbH <info@slint-ui.com>
# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

[package]
name = "slint-fmt"
version = "0.3.3"
authors = ["Slint Developers <info@slint-ui.com>"]
edition = "2021"
license = "GPL-3.0-only OR LicenseRef-Slint-commercial"
publish = false
description = "A code formatter for slint files"
repository = "https://github.com/slint-ui/slint"
homepage = "https://slint-ui.com"
categories = ["gui", "development-tools"]
keywords = ["formatter", "gui", "ui", "toolkit"]

[dependencies]
i-slint-compiler = { path = "../../internal/compiler", features = ["display-diagnostics"] }

clap = { version = "4.0", features = ["derive", "wrap_help"] }
codemap = "0.1"
codemap-diagnostic = "0.1.1"

[[bin]]
name = "slint-fmt"
path = "main.rs"
