[package]
name = "sixtyfps-fmt"
version = "0.1.2"
authors = ["SixtyFPS <info@sixtyfps.io>"]
edition = "2018"
license = "GPL-3.0-only"
publish = false
description = "Tool used to update .60 files when we do syntax upgrade"
repository = "https://github.com/sixtyfpsui/sixtyfps"
homepage = "https://sixtyfps.io"


[dependencies]
sixtyfps-compilerlib = { path = "../../sixtyfps_compiler", features = ["display-diagnostics"] }
structopt = "0.3.14"
codemap-diagnostic = "0.1.1"
codemap = "0.1"
rowan = "0.14.1"

[[bin]]
name = "sixtyfps-fmt"
path = "main.rs"
