# Copyright Â© SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-1.1 OR LicenseRef-Slint-commercial

[package]
name = "slint-fmt"
description = "A code formatter for slint files"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true
publish = false
categories = ["gui", "development-tools", "command-line-utilities"]
keywords = ["formatter", "gui", "ui", "toolkit"]

[dependencies]
i-slint-compiler = { path = "../../internal/compiler", features = ["display-diagnostics"] }

clap = { version = "4.0", features = ["derive", "wrap_help"] }
codemap = "0.1"
codemap-diagnostic = "0.1.1"

[[bin]]
name = "slint-fmt"
path = "main.rs"

[lib]
path = "lib.rs"
