# Copyright Â© SixtyFPS GmbH <info@sixtyfps.io>
# SPDX-License-Identifier: (GPL-3.0-only OR LicenseRef-SixtyFPS-commercial)

[package]
name = "sixtyfps-fmt"
version = "0.2.0"
authors = ["SixtyFPS <info@sixtyfps.io>"]
edition = "2021"
license = "(GPL-3.0-only OR LicenseRef-SixtyFPS-commercial)"
publish = false
description = "Tool used to update .slint files when we do syntax upgrade"
repository = "https://github.com/sixtyfpsui/sixtyfps"
homepage = "https://sixtyfps.io"
categories = ["gui", "development-tools"]
keywords = ["formatter", "gui", "ui", "toolkit"]

[dependencies]
slint-compiler-internal = { path = "../../internal/compiler", features = ["display-diagnostics"] }

clap = { version = "3.0.5", features=["derive", "wrap_help"] }
codemap = "0.1"
codemap-diagnostic = "0.1.1"

[[bin]]
name = "sixtyfps-fmt"
path = "main.rs"
