[package]
name = "vtable-macro"
version = "0.1.2"
authors = ["SixtyFPS <info@sixtyfps.io>"]
edition = "2018"
license = "GPL-3.0-only"
description = "Helper crate to generate ffi-friendly virtual tables"
repository = "https://github.com/sixtyfpsui/sixtyfps"
homepage = "https://sixtyfps.io"

[lib]
proc-macro = true
path = "macro.rs"

[dependencies]
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"

[dev_dependencies]
vtable = { path = ".." }
