# Copyright Â© SixtyFPS GmbH <info@sixtyfps.io>
# SPDX-License-Identifier: (GPL-3.0-only OR LicenseRef-SixtyFPS-commercial)

[package]
name = "vtable-macro"
version = "0.1.5"
authors = ["Slint Developers <info@slint-ui.com>"]
edition = "2021"
license = "(GPL-3.0-only OR LicenseRef-SixtyFPS-commercial)"
description = "Helper crate to generate ffi-friendly virtual tables"
repository = "https://github.com/slint-ui/slint"
homepage = "https://slint-ui.com"

[lib]
proc-macro = true
path = "macro.rs"

[dependencies]
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"

[dev_dependencies]
vtable = { path = ".." }
