# Copyright Â© SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: MIT OR Apache-2.0

[package]
name = "vtable-macro"
version = "0.2.1"
authors = ["Slint Developers <info@slint.dev>"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Helper crate to generate ffi-friendly virtual tables"
repository = "https://github.com/slint-ui/slint"
homepage = "https://slint.dev"

[lib]
proc-macro = true
path = "macro.rs"

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"

[dev-dependencies]
vtable = { path = ".." }
