# Copyright Â© SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: MIT

[package]
name = "ffmpeg"
version = "1.14.0"
authors = ["Slint Developers <info@slint.dev>"]
edition = "2021"
build = "build.rs"
license = "MIT"
publish = false

[[bin]]
path = "main.rs"
name = "ffmpeg"

[lib]
crate-type = ["lib", "cdylib"]
path = "lib.rs"
name = "ffmpeg_lib"

[dependencies]
slint = { path = "../../api/rs/slint", features = ["backend-android-activity-06"] }
ffmpeg-next = { version = "7.1.0" }
smol = { version = "2.0.0" }
anyhow = { version = "1.0" }
futures = { version = "0.3.28" }
cpal = "0.15.2"
ringbuf = "0.3.3"
bytemuck = "1.13.1"
derive_more = { workspace = true }

[target.'cfg(target_os = "android")'.dependencies]
ffmpeg-next = { version = "7.1.0", features = ["build"] }

[build-dependencies]
slint-build = { path = "../../api/rs/build" }

[[package.metadata.android.uses_permission]]
name = "android.permission.INTERNET"

[package.metadata.android.application]
uses_cleartext_traffic = true
