[package]
name = "sixtyfps-corelib"
version = "0.0.6"
authors = ["SixtyFPS <info@sixtyfps.io>"]
edition = "2018"
license = "GPL-3.0-only"
description = "Internal SixtyFPS runtime library."
repository = "https://github.com/sixtyfpsui/sixtyfps"
homepage = "https://sixtyfps.io"


[lib]
path = "lib.rs"

[features]
# Allow the vewer to query at runtime information about item types
rtti = []
ffi = []

[dependencies]
image = { version = "0.23.12", default-features = false, features = [ "png", "jpeg" ] }
const-field-offset = { version = "0.1", path = "../../helper_crates/const-field-offset" }
vtable = { version="0.1.1", path = "../../helper_crates/vtable" }
sixtyfps-corelib-macros = { version = "=0.0.6", path = "../corelib_macros" }
lyon_path = { version = "0.17.1" }
lyon_algorithms = { version = "0.17.1" }
lyon_geom = { version = "0.17.0" }
euclid = "0.22.1"
triomphe = "0.1.1"
once_cell = "1.5"
instant = { version = "0.1", features = [ "now" ] }
derive_more = "0.99.5"
scoped-tls-hkt = "0.1"
static_assertions = "1.1"
strum = "0.20"
strum_macros = "0.20"
slab = "0.4.3"
pin-weak = "1"
auto_enums = "0.7"
stretch = "0.3.2"
weak-table =  "0.3"
scopeguard = "1.1.0"
cfg-if = "1"
# Optional dependency to have conversion trait between femtovg::Color and sixtyfps-corelib::Color
femtovg = { version = "0.1.3", optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
instant = { version = "0.1", features = [ "wasm-bindgen", "now" ] }
web_sys = { version = "0.3", package = "web-sys", features=["console", "CanvasRenderingContext2d", "TextMetrics", "HtmlSpanElement"] }
wasm-bindgen = { version = "0.2" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
pathfinder_geometry = "0.5.1"

[dev-dependencies]
pin-weak = "1"
