# Copyright Â© SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: MIT

name: Build a WASM version of the gallery example

on:
    workflow_dispatch:
    workflow_call:

jobs:
    wasm_build:
        env:
            CARGO_PROFILE_RELEASE_OPT_LEVEL: s
            CARGO_INCREMENTAL: false
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Cache WASM build
              id: cache-wasm
              uses: actions/cache@v4
              with:
                  path: |
                      examples/gallery/pkg
                      examples/gallery/index.html
                      examples/gallery/frame-tablet.webp
                  key: wasm-build-${{ hashFiles('examples/gallery/**', 'ui/**', 'Cargo.toml', 'material.slint', 'crate/**') }}
            - name: Install Rust
              uses: dtolnay/rust-toolchain@stable
              with:
                  target: wasm32-unknown-unknown
            - name: Install wasm-pack
              run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
            - uses: Swatinem/rust-cache@v2
              with:
                  key: wasm-build
            - name: Build
              if: steps.cache-wasm.outputs.cache-hit != 'true'
              working-directory: examples/gallery
              run: wasm-pack build --target web
            - name: "Upload Artifacts"
              uses: actions/upload-artifact@v4
              with:
                  name: wasm_gallery
                  path: |
                      examples/gallery/index.html
                      examples/gallery/frame-tablet.webp
                      examples/gallery/pkg
