[package]
name = "xtask"
version = "0.1.5"
authors = ["SixtyFPS <info@sixtyfps.io>"]
edition = "2018"
license = "GPL-3.0-only"
publish = false

[dependencies]
structopt = "0.3.14"
cargo_metadata = "0.14"
anyhow = "1.0"
lazy_static = "1.4.0"
regex = "1.4"
toml_edit = "0.6.0"
xshell = "0.1.6"
serde_json = "1.0"
