# Copyright Â© SixtyFPS GmbH <info@slint-ui.com>
# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

[package]
name = "xtask"
version = "0.2.0"
authors = ["Slint Developers <info@slint-ui.com>"]
edition = "2021"
license = "GPL-3.0-only OR LicenseRef-Slint-commercial"
publish = false

[dependencies]
const_format = "0.2"
clap = { version = "3.0.5", features=["derive", "wrap_help"] }
cargo_metadata = "0.14"
anyhow = "1.0"
lazy_static = "1.4.0"
regex = "1.4"
toml_edit = "0.6.0"
xshell = "0.1.6"
serde_json = "1.0"
cbindgen = "0.20"
proc-macro2 = "1.0.11"
