# Copyright Â© SixtyFPS GmbH <info@slint-ui.com>
# SPDX-License-Identifier: MIT OR Apache-2.0

[package]
name = "const-field-offset-macro"
version = "0.1.2"
authors = ["Slint Developers <info@slint-ui.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Procedural macro to generate constant field offset from repr(c) struct"
repository = "https://github.com/slint-ui/slint"
homepage = "https://slint-ui.com"

[lib]
path = "macro.rs"
proc-macro = true

[features]
field-offset-trait = []

[dependencies]
syn = { version = "1.0", features = ["derive"] }
quote = "1.0"
proc-macro2 = "1.0"

[dev-dependencies]
memoffset = "0.7.1"
const-field-offset = { path = "..", features = ["field-offset-trait"] }
