# Copyright Â© SixtyFPS GmbH <info@sixtyfps.io>
# SPDX-License-Identifier: (GPL-3.0-only OR LicenseRef-SixtyFPS-commercial)

[package]
name = "slint-viewer"
version = "0.2.0"
authors = ["Slint Developers <info@slint-ui.com>"]
edition = "2021"
license = "(GPL-3.0-only OR LicenseRef-SixtyFPS-commercial)"
description = "Viewer binary for Slint"
repository = "https://github.com/sixtyfpsui/sixtyfps"
homepage = "https://sixtyfps.io"
categories = ["gui", "development-tools"]
keywords = ["viewer", "gui", "ui", "toolkit"]

[features]
backend-gl = ["slint-interpreter/backend-gl"]
backend-qt = ["slint-interpreter/backend-qt"]
wayland = ["slint-interpreter/wayland"]
x11 = ["slint-interpreter/x11"]

default = ["backend-qt", "backend-gl", "x11"]

[dependencies]
i-slint-core = { version = "=0.2.0", path="../../internal/core" }
slint-interpreter = { version = "=0.2.0", path = "../../internal/interpreter", default-features = false, features = ["display-diagnostics", "compat-0-2-0"] }
i-slint-backend-selector = { version = "=0.2.0", path="../../internal/backends/selector" }

vtable = { version = "0.1", path="../../helper_crates/vtable" }

clap = { version = "3.0.5", features=["derive", "wrap_help"] }
codemap = "0.1"
codemap-diagnostic = "0.1.1"
notify = "4.0.15"
serde_json = "1"
shlex = "1"
spin_on = "0.1"

[[bin]]
name = "slint-viewer"
path = "main.rs"
