# Copyright Â© SixtyFPS GmbH <info@slint-ui.com>
# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

[package]
name = "slint-viewer"
version = "0.2.2"
authors = ["Slint Developers <info@slint-ui.com>"]
edition = "2021"
license = "GPL-3.0-only OR LicenseRef-Slint-commercial"
description = "Viewer binary for Slint"
repository = "https://github.com/slint-ui/slint"
homepage = "https://slint-ui.com"
categories = ["gui", "development-tools"]
keywords = ["viewer", "gui", "ui", "toolkit"]

[features]
backend-qt = ["slint-interpreter/backend-qt"]
backend-gl-all = ["slint-interpreter/backend-gl-all"]
backend-gl-wayland = ["slint-interpreter/backend-gl-wayland"]
backend-gl-x11 = ["slint-interpreter/backend-gl-x11"]

default = ["backend-qt", "backend-gl-all"]

[dependencies]
i-slint-core = { version = "=0.2.2", path="../../internal/core" }
slint-interpreter = { version = "=0.2.2", path = "../../internal/interpreter", default-features = false, features = ["display-diagnostics", "compat-0-2-0"] }
i-slint-backend-selector = { version = "=0.2.2", path="../../internal/backends/selector" }

vtable = { version = "0.1.6", path="../../helper_crates/vtable" }

clap = { version = "3.0.5", features=["derive", "wrap_help"] }
codemap = "0.1"
codemap-diagnostic = "0.1.1"
notify = "4.0.15"
serde_json = "1"
shlex = "1"
spin_on = "0.1"

[[bin]]
name = "slint-viewer"
path = "main.rs"
