# Copyright Â© SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: MIT

[package]
name = "slint-safeui-core"
version = "1.16.0"
edition = "2024"
publish = false
build = "build.rs"
license = "MIT"

[lib]
name = "slint_safeui_core"
path = "src/lib.rs"
crate-type = ["rlib", "staticlib"]

[features]
default = ["std"]
libm = ["slint/libm"]
std = ["slint/std"]
panic-handler = []
pixel-bgra8888 = []
pixel-rgb565 = []
pixel-rgb888 = []

[dependencies]
bytemuck = "1.24.0"
slint = { path = "../../../api/rs/slint", default-features = false, features = ["compat-1-2", "renderer-software", "unsafe-single-threaded"] }

[build-dependencies]
bindgen = "0.72.1"
slint-build = { path = "../../../api/rs/build", features = ["sdf-fonts"] }
