# Copyright Â© SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: MIT

[package]
name = "uefi-demo"
version = "1.9.2"
edition = "2021"
license = "MIT"
build = "build.rs"
publish = false

[[bin]]
path = "main.rs"
name = "uefi-demo"

[target.'cfg(target_os = "uefi")'.dependencies]
uefi = { version = "0.32", features = ["panic_handler", "global_allocator"] }
minipng = "=0.1.1"

slint = { path = "../../api/rs/slint", default-features = false, features = [
    "compat-1-2",
    "renderer-software",
    "libm",
    "log",
    "unsafe-single-threaded",
] }
log = "0.4.21"

[build-dependencies]
slint-build = { path = "../../api/rs/build" }
