# Copyright Â© SixtyFPS GmbH <info@slint-ui.com>
# SPDX-License-Identifier: MIT

[package]
name = "uefi-demo"
version = "1.1.0"
edition = "2021"
license = "MIT"
build = "build.rs"
publish = false

[[bin]]
path = "main.rs"
name = "uefi-demo"

[dependencies]
uefi = "0.20.0"
uefi-services = "0.17.0"

slint = { path = "../../api/rs/slint", default-features = false, features = [
    "compat-1-0",
    "libm",
    "log",
    "unsafe-single-threaded",
] }

[build-dependencies]
slint-build = { path = "../../api/rs/build" }
