# Copyright Â© SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: MIT

[package]
name = "src"
version = "1.13.0"
authors = ["Slint Developers <info@slint.dev>"]
edition = "2021"
license = "MIT"
description = "Binaries for Rust version of Memory Tutorial of Slint"
repository = "https://github.com/slint-ui/slint"
homepage = "https://slint.dev"
publish = false

[[bin]]
name = "memory_tutorial_initial"
path = "main_initial.rs"

[[bin]]
name = "memory_tutorial_tile"
path = "main_memory_tile.rs"

[[bin]]
name = "memory_tutorial_polishing_the_tile"
path = "main_polishing_the_tile.rs"

[[bin]]
name = "memory_tutorial_multiple_tiles"
path = "main_multiple_tiles.rs"

[[bin]]
name = "memory_tutorial_tiles_from_rust"
path = "main_tiles_from_rust.rs"

[[bin]]
name = "memory_tutorial_game_logic_in_rust"
path = "main_game_logic_in_rust.rs"

[dependencies]
slint = { path = "../../../../api/rs/slint" }
rand = "0.8"
