# Copyright Â© SixtyFPS GmbH <info@slint-ui.com>
# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

[package]
name = "printerdemo_mcu"
version = "0.2.4"
authors = ["Slint Developers <info@slint-ui.com>"]
edition = "2021"
build = "build.rs"
publish = false
license = "GPL-3.0-only OR LicenseRef-Slint-commercial"

[[bin]]
path = "main.rs"
name = "printerdemo_mcu"

[features]
mcu-simulator = ["i-slint-backend-mcu/simulator"]
mcu-pico-st7789 = ["i-slint-backend-mcu/pico-st7789"]

[dependencies]
slint = { path = "../../api/rs/slint", default-features = false, features = ["compat-0-2-0"] }
i-slint-backend-mcu = { path = "../../internal/backends/mcu", default-features = false }
chrono = { version = "0.4", default-features = false, features = ["clock", "std"], optional = true }

[build-dependencies]
slint-build = { path = "../../api/rs/build" }

