# Copyright Â© SixtyFPS GmbH <info@slint-ui.com>
# SPDX-License-Identifier: MIT

[package]
name = "printerdemo_mcu"
version = "1.1.0"
authors = ["Slint Developers <info@slint-ui.com>"]
edition = "2021"
build = "build.rs"
publish = false
license = "MIT"

[[bin]]
path = "main.rs"
name = "printerdemo_mcu"

[features]
simulator = ["slint/renderer-winit-software", "slint/backend-winit", "slint/std"]
default = ["simulator"]

[dependencies]
slint = { path = "../../api/rs/slint", default-features = false, features = ["compat-1-0"] }
mcu-board-support = { path = "../mcu-board-support" }

[build-dependencies]
slint-build = { path = "../../api/rs/build" }

