[package]
name = "sixtyfps"
version = "0.0.5"
authors = ["SixtyFPS <info@sixtyfps.io>"]
edition = "2018"
license = "GPL-3.0-only"
description = "SixtyFPS Rust API"
repository = "https://github.com/sixtyfpsui/sixtyfps"
homepage = "https://sixtyfps.io"

[lib]
path = "lib.rs"

[features]
x11 = ["sixtyfps-rendering-backend-default/x11"]
wayland = ["sixtyfps-rendering-backend-default/wayland"]
backend-gl = ["sixtyfps-rendering-backend-default/sixtyfps-rendering-backend-gl"]
backend-qt = ["sixtyfps-rendering-backend-default/sixtyfps-rendering-backend-qt"]
default = ["backend-gl", "backend-qt"]

[dependencies]
once_cell = "1.5"
sixtyfps-macros = { version = "=0.0.5", path = "sixtyfps-macros" }
const-field-offset = { version = "0.1", path = "../../helper_crates/const-field-offset" }
vtable = { version = "0.1.1", path = "../../helper_crates/vtable" }
sixtyfps-corelib = { version = "=0.0.5", path="../../sixtyfps_runtime/corelib" }
sixtyfps-rendering-backend-default = { version = "=0.0.5", path="../../sixtyfps_runtime/rendering_backends/default" }
pin-weak = "1"

[build-dependencies]
rustc_version = "0.3"

[package.metadata.docs.rs]
rustdoc-args = [ "--html-in-header", "sixtyfps-docs-integration.html" ]
