# Copyright Â© SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: MIT

[package]
name = "slide_puzzle"
version = "1.12.0"
authors = ["Slint Developers <info@slint.dev>"]
edition = "2021"
publish = false
license = "MIT"

[[bin]]
path = "main.rs"
name = "slide_puzzle"

[dependencies]
rand = "0.8"
slint = { path = "../../api/rs/slint" }

[build-dependencies]
slint-build = { path = "../../api/rs/build" }

# Remove the `#wasm#` to uncomment the wasm build.
# This is commented out by default because we don't want to build it as a library by default
# The CI has a script that does sed "s/#wasm# //" to generate the wasm build.

#wasm# [lib]
#wasm# path = "main.rs"
#wasm# crate-type = ["cdylib"]

#wasm# [target.'cfg(target_arch = "wasm32")'.dependencies]
#wasm# wasm-bindgen = { version = "0.2" }
#wasm# web-sys = { version = "0.3", features=["console", "Element", "HtmlCollection"] }
#wasm# console_error_panic_hook = "0.1.5"
#wasm# getrandom = { version = "0.2.2", features = ["js"] }
