# Copyright Â© SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: MIT

[package]
name = "slide_puzzle"
version = "1.6.0"
authors = ["Slint Developers <info@slint.dev>"]
edition = "2021"
publish = false
license = "MIT"

[[bin]]
path = "main.rs"
name = "slide_puzzle"

[lib]
path = "main.rs"

[features]
default = ["slint/default", "rand"]
from_launcher = []

[dependencies]
rand = { version = "0.8", optional = true, default-features = false, features = ["small_rng", "getrandom"] }
slint = { path = "../../api/rs/slint", default-features = false, features = ["compat-1-0"] }
i-slint-core = { path = "../../internal/core", default-features = false, features = ["libm"] }
mcu-board-support = { path = "../mcu-board-support", optional = true }
once_cell = { version="1.9", features = ["atomic-polyfill"], default-features = false }
getrandom = { version = "0.2", default-features = false, features = ["custom"] }

[build-dependencies]
slint-build = { path = "../../api/rs/build" }

# Remove the `#wasm#` to uncomment the wasm build.
# This is commented out by default because we don't want to build it as a library by default
# The CI has a script that does sed "s/#wasm# //" to generate the wasm build.

#wasm# [lib]
#wasm# path = "main.rs"
#wasm# crate-type = ["cdylib"]

#wasm# [target.'cfg(target_arch = "wasm32")'.dependencies]
#wasm# wasm-bindgen = { version = "0.2" }
#wasm# web-sys = { version = "0.3", features=["console", "Element", "HtmlCollection"] }
#wasm# console_error_panic_hook = "0.1.5"
#wasm# getrandom = { version = "0.2.2", features = ["js"] }
