# Copyright Â© 2024 Slint project authors (see AUTHORS or LICENSE-MIT)
# SPDX-License-Identifier: MIT

[workspace]

[package]
name = "bevy-hosts-slint"
version = "1.16.0"
authors = ["Slint Developers <info@slint.dev>"]
edition = "2024"
publish = false
license = "MIT"
description = "Slint Bevy Integration Example"

[[bin]]
name = "bevy_example"
path = "main.rs"

[dependencies]
slint = { path = "../../../slint/api/rs/slint", default-features = false, features = ["compat-1-2", "renderer-software", "software-renderer-systemfonts", "std"] }
bevy = { version = "0.18.0" }
bevy_image = { version = "0.18.0", features = ["zstd_rust"] }
bytemuck = "1.13.1"
