# Copyright Â© SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: MIT

[package]
name = "virtual_keyboard"
version = "v1.15.1"
authors = ["Slint Developers <info@slint.dev>"]
edition.workspace = true
build = "build.rs"
publish = false
license = "MIT"

[[bin]]
path = "main.rs"
name = "virtual_keyboard"

[dependencies]
slint = { path = "../../../api/rs/slint" }

[build-dependencies]
slint-build = { path = "../../../api/rs/build" }
