# Copyright Â© SixtyFPS GmbH <info@slint-ui.com>
# SPDX-License-Identifier: MIT

[package]
name = "virtual_keyboard"
version = "1.1.0"
authors = ["Slint Developers <info@slint-ui.com>"]
edition = "2021"
build = "build.rs"
publish = false
license = "MIT"

[[bin]]
path = "main.rs"
name = "virtual_keyboard"

[dependencies]
slint = { path = "../../../api/rs/slint" }

[build-dependencies]
slint-build = { path = "../../../api/rs/build" }
