# Copyright Â© SixtyFPS GmbH <info@slint-ui.com>
# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

[package]
name = "i-slint-core-macros"
version = "0.3.4"
authors = ["Slint Developers <info@slint-ui.com>"]
edition = "2021"
license = "GPL-3.0-only OR LicenseRef-Slint-commercial"
description = "Helper macro for i-slint-core"
repository = "https://github.com/slint-ui/slint"
homepage = "https://slint-ui.com"


[lib]
proc-macro = true
path = "lib.rs"

[dependencies]
quote = "1.0"
syn = "1.0"
