# Copyright Â© SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-1.0 OR LicenseRef-Slint-commercial

[package]
name = "i-slint-core-macros"
version = "1.1.1"
authors = ["Slint Developers <info@slint.dev>"]
edition = "2021"
license = "GPL-3.0-only OR LicenseRef-Slint-Royalty-free-1.0 OR LicenseRef-Slint-commercial"
description = "Helper macro for i-slint-core"
repository = "https://github.com/slint-ui/slint"
homepage = "https://slint.dev"


[lib]
proc-macro = true
path = "lib.rs"

[dependencies]
quote = "1.0"
syn = "2.0"
