[package]
name = "figma_import"
version = "0.1.4"
authors = ["SixtyFPS <info@sixtyfps.io>"]
edition = "2018"
license = "GPL-3.0-only"
publish = false

[dependencies]
float-cmp = "0.9.0"
structopt = "0.3"
reqwest = { version = "0.11", features = ["json", "stream"] }
tokio = { version = "1", features = ["full"] }
futures = "0.3"
serde = { version = "1.0.123", features = ["derive"] }
serde_json = "1"
smart-default = "0.6"
derive_more = "0.99"


[workspace]
#
