# Copyright Â© SixtyFPS GmbH <info@slint-ui.com>
# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

[package]
name = "figma_import"
version = "1.1.0"
authors = ["Slint Developers <info@slint-ui.com>"]
description = "A figma file importer for Slint"
edition = "2021"
license = "GPL-3.0-only"
publish = false

[dependencies]
float-cmp = "0.9.0"
clap = { version = "4.0", features = ["derive", "wrap_help"] }
reqwest = { version = "0.11", features = ["json", "stream"] }
tokio = { version = "1", features = ["full"] }
futures = "0.3"
serde = { version = "1.0.123", features = ["derive"] }
serde_json = "1"
smart-default = "0.6"
derive_more = "0.99"


[workspace]
#
