# Copyright Â© SixtyFPS GmbH <info@slint-ui.com>
# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

[package]
name = "i-slint-backend-gl"
version = "0.2.6"
authors = ["Slint Developers <info@slint-ui.com>"]
edition = "2021"
license = "GPL-3.0-only OR LicenseRef-Slint-commercial"
description = "OpenGL rendering backend for Slint"
repository = "https://github.com/slint-ui/slint"
homepage = "https://slint-ui.com"

[lib]
path = "lib.rs"

# Note, these features need to be kept in sync (along with their defaults) in
# the C++ crate's CMakeLists.txt
[features]
svg = ["resvg", "usvg", "tiny-skia"]
wayland = ["winit/wayland", "glutin/wayland", "copypasta/wayland"]
x11 = ["winit/x11", "glutin/x11", "copypasta/x11"]

rtti = ["i-slint-core/rtti"]

default = ["svg"]

[dependencies]
i-slint-core = { version = "=0.2.6", path = "../../../internal/core" }
i-slint-core-macros = { version = "=0.2.6", path = "../../../internal/core-macros" }
i-slint-common = { version = "=0.2.6", path = "../../../internal/common" }

const-field-offset = { version = "0.1", path = "../../../helper_crates/const-field-offset" }
vtable = { version = "0.1.6", path = "../../../helper_crates/vtable" }

by_address = "1.0.4"
cfg-if = "1"
copypasta = { version = "0.8.1", default-features = false }
derive_more = "0.99.5"
euclid = "0.22.1"
femtovg = { version = "0.3.5" }
fontdb = { version = "0.9.0", default-features = false }
image = { version = "0.24.0", default-features = false, features = [ "png", "jpeg" ] }
imgref = "1.6.1"
lyon_path = "0.17.3"
once_cell = "1.5"
pin-weak = "1"
resvg = { version= "0.23", optional = true, default-features = false }
rgb = "0.8.27"
scoped-tls-hkt = "0.1"
tiny-skia = { version= "0.6", optional = true, default-features = false }
ttf-parser = "0.15.0" # Use the same version was femtovg's rustybuzz, to avoid duplicate crates
unicode-script = "0.5.4" # Use the same version was femtovg's rustybuzz, to avoid duplicate crates
usvg = { version= "0.23", optional = true, default-features = false, features = ["text"] }
winit = { version = "0.26", default-features = false }
dark-light = "0.2.2"

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { version = "0.3", features=["console", "WebGlContextAttributes", "CanvasRenderingContext2d", "HtmlInputElement", "HtmlCanvasElement", "Window", "Document", "CssStyleDeclaration", "Event", "KeyboardEvent", "InputEvent", "CompositionEvent"] }
wasm-bindgen = { version = "0.2" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
fontdb = { version = "0.9.0", features = ["memmap", "fontconfig"] }
glutin = { version = "0.28", default-features = false }
usvg = { version= "0.23", optional = true, default-features = false, features = ["text", "memmap-fonts"] }

[target.'cfg(target_family = "windows")'.dependencies]
dwrote = "0.11.0"
winapi = { version = "0.3", features = ["dwrite"] }

[target.'cfg(not(any(target_family = "windows", target_os = "macos", target_os = "ios", target_arch = "wasm32")))'.dependencies]
libc = { version = "0.2" }
# Require font-config from the system on Linux. Issue #88 indicates that the copy provided by servo-fontconfig may be incompatible
# with distros at times.
servo-fontconfig = { version = "0.5", features = [ "force_system_lib" ] }

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = { version = "0.24.0" }
core-foundation = { version = "0.9.1" }
core-text = { version = "19.1.0" }
