# Copyright Â© SixtyFPS GmbH <info@slint-ui.com>
# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

[package]
name = "i-slint-backend-mcu"
version = "0.2.0"
authors = ["Slint Developers <info@slint-ui.com>"]
edition = "2021"
license = "GPL-3.0-only OR LicenseRef-Slint-commercial"
publish = false
description = "Rendering backend for Slint for use on Microcontrollers"
repository = "https://github.com/slint-ui/slint"
homepage = "https://slint-ui.com"

[lib]
path = "lib.rs"

[features]
simulator = ["winit", "glutin", "femtovg", "embedded-graphics-simulator", "std", "imgref", "scoped-tls-hkt"]

pico-st7789 = ["unsafe_single_core", "rp-pico", "embedded-hal", "cortex-m-rt", "alloc-cortex-m", "embedded-time", "cortex-m", "display-interface-spi", "st7789", "defmt", "defmt-rtt",  "i-slint-core/defmt", "shared-bus" ]

unsafe_single_core = ["i-slint-core/unsafe_single_core"]

snapshot_renderer = []
std = ["i-slint-core/std"]

default = ["simulator"]

[dependencies]
i-slint-common = { version = "=0.2.0", path = "../../../internal/common", default-features = false }
i-slint-core = { version = "=0.2.0", path = "../../../internal/core", default-features = false }

const-field-offset = { version = "0.1", path = "../../../helper_crates/const-field-offset" }
vtable = { version = "0.1", path = "../../../helper_crates/vtable" }

by_address = "1.0.4"
derive_more = "0.99.5"
embedded-graphics = "0.7.1"
embedded-graphics-simulator = { version = "0.3.0", optional = true, default-features = false }
euclid = { version = "0.22.1", default-features = false }
femtovg = { version = "0.3.0", optional = true }
glutin = { version = "0.28", default-features = false, optional = true, features = ["x11"] }
imgref = { version = "1.6.1", optional = true }
once_cell = { version = "1.9", default-features = false, features = ["alloc", "atomic-polyfill"] }
pin-weak = { version = "1", default-features = false }
rgb = "0.8.27"
scoped-tls-hkt = { version = "0.1", optional = true }
winit = { version = "0.26.0", default-features = false, optional = true, features = ["x11"] }

alloc-cortex-m = { version = "0.4.1", optional = true }
cortex-m-rt = { version = "0.7", optional = true }
cortex-m = { version = "0.7.2", optional = true }
display-interface-spi = { version = "0.4.1", optional = true }
embedded-hal = { version = "0.2.5", optional = true }
embedded-time = { version = "0.12.0", optional = true }
rp-pico = { version = "0.2.0", optional = true }
shared-bus = { version = "0.2", optional = true }
st7789 = { version = "0.6.1", optional = true }

defmt-rtt = { version = "0.3.0", optional = true }
defmt = { version = "0.3.0", optional = true }
panic-probe = { version = "0.3.0", optional = true, features = ["print-defmt"] }

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = { version = "0.24.0" }
