# Copyright Â© SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: MIT

[package]
name = "printerdemo"
version = "1.5.0"
authors = ["Slint Developers <info@slint.dev>"]
edition = "2021"
build = "build.rs"
publish = false
license = "MIT"

[[bin]]
path = "main.rs"
name = "printerdemo"

[dependencies]
slint = { path = "../../../api/rs/slint", features = ["backend-android-activity-05"] }

chrono = { version = "0.4", default-features = false, features = ["clock", "std"]}

[build-dependencies]
slint-build = { path = "../../../api/rs/build" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { version = "0.2" }
web-sys = { version = "0.3", features=["console"] }
console_error_panic_hook = "0.1.5"

# Remove the `#wasm#` to uncomment the wasm or android build.
# This is commented out by default because we don't want to build it as a library by default
# The CI has a script that does sed "s/#wasm# //" to generate the wasm build.

#wasm# [lib]
#wasm# path = "main.rs"
#wasm# crate-type = ["cdylib"]





