# Copyright Â© SixtyFPS GmbH <info@slint-ui.com>
# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

[package]
name = "slint-node"
version = "0.3.2"
authors = ["Slint Developers <info@slint-ui.com>"]
edition = "2021"
build = "build.rs"
# This is not meant to be used as a library from crate.io
publish = false
license = "GPL-3.0-only OR LicenseRef-Slint-commercial"
repository = "https://github.com/slint-ui/slint"
homepage = "https://slint-ui.com"


[lib]
path = "lib.rs"
crate-type = ["cdylib"]
name = "slint_node_native"

[dependencies]
i-slint-compiler = { version = "=0.3.2", path="../../../internal/compiler" }
i-slint-core = { version = "=0.3.2", path="../../../internal/core" }
slint-interpreter = { version = "=0.3.2", path="../../../internal/interpreter",  features = ["display-diagnostics"] }

vtable = { version = "0.1.6", path="../../../helper_crates/vtable" }

css-color-parser2 = "1.0.1"
generativity = "1"
neon = "0.8.0"
once_cell = "1.5"
rand = "0.8"
scoped-tls-hkt = "0.1"
spin_on = "0.1" #FIXME: remove and delegate to async JS instead

[build-dependencies]
neon-build = "0.8.0"
