# Copyright Â© SixtyFPS GmbH <info@sixtyfps.io>
# SPDX-License-Identifier: (GPL-3.0-only OR LicenseRef-SixtyFPS-commercial)

[package]
name = "slint-backend-testing-internal"
version = "0.2.0"
authors = ["SixtyFPS <info@sixtyfps.io>"]
edition = "2021"
license = "(GPL-3.0-only OR LicenseRef-SixtyFPS-commercial)"
description = "OpenGL rendering backend for Slint"
repository = "https://github.com/sixtyfpsui/sixtyfps"
homepage = "https://sixtyfps.io"
publish = false

[lib]
path = "lib.rs"

[dependencies]
slint-core-internal = { version = "=0.2.0", path = "../../../internal/core" }

image = { version = "0.23.14", default-features = false, features = ["png"] }
