# Copyright Â© SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-1.1 OR LicenseRef-Slint-commercial

[package]
name = "i-slint-backend-testing"
version = "1.2.0"
authors = ["Slint Developers <info@slint.dev>"]
edition = "2021"
license = "GPL-3.0-only OR LicenseRef-Slint-Royalty-free-1.1 OR LicenseRef-Slint-commercial"
description = "OpenGL rendering backend for Slint"
repository = "https://github.com/slint-ui/slint"
homepage = "https://slint.dev"
publish = false

[lib]
path = "lib.rs"

[dependencies]
i-slint-core = { version = "=1.2.0", path = "../../../internal/core" }
vtable = { version = "0.1.8", path = "../../../helper_crates/vtable" }
image = { version = "0.24.0", default-features = false, features = ["png", "jpeg"] }
