[package]
name = "sixtyfps-rendering-backend-default"
version = "0.1.6"
authors = ["SixtyFPS <info@sixtyfps.io>"]
edition = "2018"
license = "GPL-3.0-only"
description = "Helper crate to pick the default rendering backend for SixtyFPS"
repository = "https://github.com/sixtyfpsui/sixtyfps"
homepage = "https://sixtyfps.io"

[lib]
path = "lib.rs"

[features]
x11 = ["sixtyfps-rendering-backend-gl/x11"]
wayland = ["sixtyfps-rendering-backend-gl/wayland"]

[dependencies]
sixtyfps-corelib = { version = "=0.1.6", path = "../../corelib" }
sixtyfps-rendering-backend-gl = { version = "=0.1.6", path = "../gl", optional = true }
sixtyfps-rendering-backend-qt = { version = "=0.1.6", path = "../qt", optional = true }
cfg-if = "1"
once_cell = "1.5"
