# Copyright Â© SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: MIT

[package]
name = "slint-safeui-simulator"
version = "1.16.0"
edition = "2024"
publish = false
license = "MIT"

[features]
default = []
pixel-bgra8888 = ["slint-safeui-core/pixel-bgra8888"]
pixel-rgb565 = ["slint-safeui-core/pixel-rgb565"]
pixel-rgb888 = ["slint-safeui-core/pixel-rgb888"]

[dependencies]
bytemuck = "1.24.0"
slint = { path = "../../../api/rs/slint" }
slint-safeui-core = { path = "../core", features = ["std"] }
i-slint-backend-selector = { path = "../../../internal/backends/selector", default-features = false }

smol = "2.0.0"
