# Copyright Â© SixtyFPS GmbH <info@sixtyfps.io>
# SPDX-License-Identifier: (GPL-3.0-only OR LicenseRef-SixtyFPS-commercial)

[package]
name = "sixtyfps-rendering-backend-mcu"
version = "0.1.6"
authors = ["SixtyFPS <info@sixtyfps.io>"]
edition = "2018"
license = "(GPL-3.0-only OR LicenseRef-SixtyFPS-commercial)"
publish = false
description = "Rendering backend for SixtyFPS for use on Microcontrollers"
repository = "https://github.com/sixtyfpsui/sixtyfps"
homepage = "https://sixtyfps.io"

[lib]
path = "lib.rs"

[features]
simulator = ["winit", "glutin", "femtovg", "embedded-graphics-simulator", "std", "imgref", "scoped-tls-hkt"]
default = ["simulator"]

pico-st7789 = ["unsafe_single_core", "rp-pico", "embedded-hal", "cortex-m-rt", "alloc-cortex-m", "embedded-time", "cortex-m", "display-interface-spi", "st7789", "defmt", "defmt-rtt", "panic-probe", "sixtyfps-corelib/defmt" ]

unsafe_single_core = ["sixtyfps-corelib/unsafe_single_core"]

snapshot_renderer = []
std = ["sixtyfps-corelib/std"]

[dependencies]
sixtyfps-corelib = { version = "=0.1.6", path = "../../corelib", default-features = false }
sixtyfps-common = { version = "=0.1.6", path = "../../common", default-features = false }
const-field-offset = { version = "0.1", path = "../../../helper_crates/const-field-offset" }
rgb = "0.8.27"
vtable = { version = "0.1", path = "../../../helper_crates/vtable" }
by_address = "1.0.4"
euclid = { version = "0.22.1", default-features = false }
pin-weak = { version = "1", default-features = false }
once_cell = { version = "1.9", default-features = false, features = ["alloc", "atomic-polyfill"] }
derive_more = "0.99.5"
winit = { version = "0.26.0", default-features = false, optional = true, features = ["x11"] }
glutin = { version = "0.28", default-features = false, optional = true, features = ["x11"] }
femtovg = { version = "0.2.9", optional = true }
scoped-tls-hkt = { version = "0.1", optional = true }
imgref = { version = "1.6.1", optional = true }
embedded-graphics = "0.7.1"
embedded-graphics-simulator = { version = "0.3.0", optional = true, default-features = false }

rp-pico = { version = "0.2.0", optional = true }
embedded-hal = { version = "0.2.5", optional = true }
cortex-m-rt = { version = "0.7", optional = true }
alloc-cortex-m = { version = "0.4.1", optional = true }
panic-halt= { version = "0.2.0", optional = true }
embedded-time = { version = "0.12.0", optional = true }
cortex-m = { version = "0.7.2", optional = true }
display-interface-spi = { version = "0.4.1", optional = true }
st7789 = { version = "0.6.1", optional = true }

defmt = { version = "0.3.0", optional = true }
defmt-rtt = { version = "0.3.0", optional = true }
panic-probe = { version = "0.3.0", optional = true, features = ["print-defmt"] }

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = { version = "0.24.0" }


