[package]
name = "_7gui"
version = "0.1.5"
authors = ["SixtyFPS <info@sixtyfps.io>"]
edition = "2018"
publish = false
license = "GPL-3.0-only"

[[bin]]
path = "booker.rs"
name = "booker"

[dependencies]
sixtyfps = { path = "../../api/sixtyfps-rs" }
chrono = { version = "0.4", default-features = false, features = ["clock", "std"]}
