# Copyright Â© SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: MIT OR Apache-2.0

[package]
name = "vtable"
version = "0.3.0"
authors = ["Slint Developers <info@slint.dev>"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Helper crate to generate ffi-friendly virtual tables"
repository = "https://github.com/slint-ui/slint"
homepage = "https://slint.dev"

[lib]

[dependencies]
vtable-macro = { version = "=0.3.0", path = "./macro" }
const-field-offset = { version = "0.1", path = "../const-field-offset" }
stable_deref_trait = { version = "1.2.0", default-features = false }
portable-atomic = "1"
