[package]
name = "vtable"
version = "0.1.5"
authors = ["SixtyFPS <info@sixtyfps.io>"]
edition = "2018"
license = "GPL-3.0-only"
description = "Helper crate to generate ffi-friendly virtual tables"
repository = "https://github.com/sixtyfpsui/sixtyfps"
homepage = "https://sixtyfps.io"

[lib]

[dependencies]
vtable-macro = { version = "=0.1.5", path = "./macro" }
const-field-offset = { version = "0.1", path = "../const-field-offset" }
stable_deref_trait = { version = "1.2.0", default-features = false }
atomic-polyfill = "0.1.5"
