# Copyright Â© SixtyFPS GmbH <info@slint-ui.com>
# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-1.0 OR LicenseRef-Slint-commercial

[package]
name = "vtable"
version = "0.1.10"
authors = ["Slint Developers <info@slint-ui.com>"]
edition = "2021"
license = "GPL-3.0-only OR LicenseRef-Slint-Royalty-free-1.0 OR LicenseRef-Slint-commercial"
description = "Helper crate to generate ffi-friendly virtual tables"
repository = "https://github.com/slint-ui/slint"
homepage = "https://slint-ui.com"

[lib]

[dependencies]
vtable-macro = { version = "=0.1.10", path = "./macro" }
const-field-offset = { version = "0.1", path = "../const-field-offset" }
stable_deref_trait = { version = "1.2.0", default-features = false }
atomic-polyfill = "1.0.1"
