[package]
name = "sixtyfps-rendering-backend-qt"
version = "0.1.5"
authors = ["SixtyFPS <info@sixtyfps.io>"]
edition = "2018"
license = "GPL-3.0-only"
description = "Qt rendering backend for SixtyFPS"
repository = "https://github.com/sixtyfpsui/sixtyfps"
homepage = "https://sixtyfps.io"
links = "sixtyfps_rendering_backend_qt" # just so we can pass metadata to the dependee's build script

[features]
rtti = ["sixtyfps-corelib/rtti"]
default = ["rtti"]

[lib]
path = "lib.rs"

[dependencies]
cpp = "0.5.5"
const-field-offset = { version = "0.1", path = "../../../helper_crates/const-field-offset" }
vtable = { version = "0.1", path = "../../../helper_crates/vtable" }
sixtyfps-corelib-macros = { version = "=0.1.5", path = "../../corelib_macros" }
sixtyfps-corelib = { version = "=0.1.5", path = "../../corelib" }
euclid = "0.22.1"
pin-weak = "1"
once_cell = "1"
lyon_path = "0.17"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
qttypes = { version = "0.2.5", default-features = false }

[build-dependencies]
cpp_build = "0.5.5"
