# Copyright Â© SixtyFPS GmbH <info@slint-ui.com>
# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

[package]
name = "syntax_updater"
version = "0.3.1"
authors = ["Slint Developers <info@slint-ui.com>"]
edition = "2021"
license = "GPL-3.0-only OR LicenseRef-Slint-commercial"
publish = false
description = "Tool used to update .slint files when we do syntax upgrade"
repository = "https://github.com/slint-ui/slint"
homepage = "https://slint-ui.com"


[dependencies]
i-slint-compiler = { path = "../../internal/compiler", features = ["display-diagnostics"] }

clap = { version = "3.2", features = ["derive", "wrap_help"] }
codemap = "0.1"
codemap-diagnostic = "0.1.1"
spin_on = "0.1"

[[bin]]
name = "syntax_updater"
path = "main.rs"
