# Copyright Â© SixtyFPS GmbH <info@slint-ui.com>
# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

[package]
name = "i-slint-backend-qt"
version = "1.0.1"
authors = ["Slint Developers <info@slint-ui.com>"]
edition = "2021"
license = "GPL-3.0-only OR LicenseRef-Slint-commercial"
description = "Qt rendering backend for Slint"
repository = "https://github.com/slint-ui/slint"
homepage = "https://slint-ui.com"
links = "i_slint_backend_qt" # just so we can pass metadata to the dependee's build script

[features]
rtti = ["i-slint-core/rtti"]

[lib]
path = "lib.rs"

[dependencies]
i-slint-common = { version = "=1.0.1", path = "../../../internal/common" }
i-slint-core-macros = { version = "=1.0.1", path = "../../../internal/core-macros" }
i-slint-core = { version = "=1.0.1", path = "../../../internal/core" }

const-field-offset = { version = "0.1", path = "../../../helper_crates/const-field-offset" }
vtable = { version = "0.1.8", path = "../../../helper_crates/vtable" }

cpp = "0.5.5"
lyon_path = "1"
once_cell = "1"
pin-project = "1"
pin-weak = "1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
qttypes = { version = "0.2.7", default-features = false }

[build-dependencies]
cpp_build = "0.5.5"
