[package]
name = "sixtyfps-compiler"
version = "0.1.6"
authors = ["SixtyFPS <info@sixtyfps.io>"]
edition = "2018"
license = "GPL-3.0-only"
description = "SixtyFPS compiler binary"
repository = "https://github.com/sixtyfpsui/sixtyfps"
homepage = "https://sixtyfps.io"

[[bin]]
name = "sixtyfps-compiler"
path = "main.rs"

[dependencies]
sixtyfps-compilerlib = { version = "=0.1.6", path = "../../sixtyfps_compiler", features = ["display-diagnostics", "cpp", "rust"]}
structopt = "0.3.14"
spin_on = "0.1"
proc-macro2 = "1.0.11"
