# Copyright Â© SixtyFPS GmbH <info@sixtyfps.io>
# SPDX-License-Identifier: (GPL-3.0-only OR LicenseRef-SixtyFPS-commercial)

[package]
name = "slint-compiler"
version = "0.2.0"
authors = ["Slint Developers <info@slint-ui.com>"]
edition = "2021"
license = "(GPL-3.0-only OR LicenseRef-SixtyFPS-commercial)"
description = "Slint compiler binary"
repository = "https://github.com/sixtyfpsui/sixtyfps"
homepage = "https://sixtyfps.io"
publish = false

[[bin]]
name = "slint-compiler"
path = "main.rs"

[dependencies]
i-slint-compiler = { version = "=0.2.0", path = "../../internal/compiler", features = ["display-diagnostics", "cpp", "rust"]}

clap = { version = "3.0.5", features=["derive", "wrap_help"] }
proc-macro2 = "1.0.11"
spin_on = "0.1"
