# Copyright Â© SixtyFPS GmbH <info@slint-ui.com>
# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

[package]
name = "slint-compiler"
version = "0.3.5"
authors = ["Slint Developers <info@slint-ui.com>"]
edition = "2021"
license = "GPL-3.0-only OR LicenseRef-Slint-commercial"
description = "Slint compiler binary"
repository = "https://github.com/slint-ui/slint"
homepage = "https://slint-ui.com"
publish = false

[[bin]]
name = "slint-compiler"
path = "main.rs"

[dependencies]
i-slint-compiler = { version = "=0.3.5", path = "../../internal/compiler", features = ["display-diagnostics", "cpp", "rust"]}

clap = { version = "4.0", features = ["derive", "wrap_help"] }
proc-macro2 = "1.0.11"
spin_on = "0.1"
