# Copyright Â© SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-1.1 OR LicenseRef-Slint-commercial

[package]
name = "slint-compiler"
description = "Slint compiler binary"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true
publish = false

[[bin]]
name = "slint-compiler"
path = "main.rs"

[features]
software-renderer = ["i-slint-compiler/software-renderer"]

default = ["software-renderer"]

[dependencies]
i-slint-compiler = { version = "=1.3.0", path = "../../internal/compiler", features = ["display-diagnostics", "cpp", "rust"]}

clap = { version = "4.0", features = ["derive", "wrap_help"] }
proc-macro2 = "1.0.11"
spin_on = "0.1"
