# Copyright Â© SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

[package]
name = "i-slint-common"
description = "Helper crate for sharing code & data structures between i-slint-core and slint-compiler"
authors.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
path = "lib.rs"

[features]
default = []
shared-fontdb = ["dep:fontdb", "dep:libloading", "derive_more", "cfg-if", "dep:ttf-parser"]

[dependencies]
fontdb = { workspace = true, optional = true }
ttf-parser = { workspace = true, optional = true }
derive_more = { workspace = true, optional = true }
cfg-if = { version = "1", optional = true }

[target.'cfg(not(any(target_family = "windows", target_vendor = "apple", target_arch = "wasm32", target_os = "android")))'.dependencies]
libloading = { version = "0.8.0", optional = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
fontdb = { workspace = true, optional = true, features = ["std", "fs", "fontconfig"] }

[target.'cfg(all(not(target_arch = "wasm32"), not(target_os = "nto")))'.dependencies]
fontdb = { workspace = true, optional = true, features = ["memmap"] }

[package.metadata.docs.rs]
rustdoc-args = ["--generate-link-to-definition"]
