# Copyright Â© SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

[package]
name = "i-slint-common"
description = "Helper crate for sharing code & data structures between i-slint-core and slint-compiler"
authors.workspace = true
documentation.workspace = true
edition = "2024"
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
path = "lib.rs"

[features]
default = []
shared-fontique = ["dep:fontique", "dep:ttf-parser"]
color-parsing = []
fontconfig-dlopen = ["fontique?/fontconfig-dlopen"]
markdown = ["dep:pulldown-cmark", "dep:htmlparser", "dep:thiserror", "color-parsing"]

[dependencies]
ttf-parser = { workspace = true, optional = true }
fontique = { workspace = true, optional = true }
pulldown-cmark = { version = "0.13.0", optional = true }
htmlparser = { version = "0.2.1", optional = true }
thiserror = { version = "2.0.17", optional = true }

[package.metadata.docs.rs]
rustdoc-args = ["--generate-link-to-definition"]
