# Copyright Â© SixtyFPS GmbH <info@slint-ui.com>
# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

[package]
name = "i-slint-common"
version = "1.0.0"
authors = ["Slint Developers <info@slint-ui.com>"]
edition = "2021"
license = "GPL-3.0-only OR LicenseRef-Slint-commercial"
description = "Helper crate for sharing code & data structures between i-slint-core and slint-compiler"
repository = "https://github.com/slint-ui/slint"
homepage = "https://slint-ui.com"


[lib]
path = "lib.rs"
