[package]
name = "sixtyfps-corelib-macros"
version = "0.0.2"
authors = ["SixtyFPS <info@sixtyfps.io>"]
edition = "2018"
license = "GPL-3.0-only"
description = "Helper macro for sixtyfps-corelib"
repository = "https://github.com/sixtyfpsui/sixtyfps"
homepage = "https://sixtyfps.io"


[lib]
proc-macro = true
path = "lib.rs"

[dependencies]
quote = "1.0"
syn = "1.0"
