# Copyright Â© SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: MIT

[package]
name = "maps"
version = "1.12.0"
authors = ["Slint Developers <info@slint.dev>"]
edition = "2021"
license = "MIT"
publish = false

[[bin]]
path = "main.rs"
name = "maps"

[dependencies]
slint = { path = "../../api/rs/slint" }
image = { workspace = true }
reqwest = { version = "0.12" }
tokio = { version = "1", features = ["full"] }
