# Copyright Â© SixtyFPS GmbH <info@sixtyfps.io>
# SPDX-License-Identifier: (GPL-3.0-only OR LicenseRef-SixtyFPS-commercial)

[package]
name = "sixtyfps-node"
version = "0.2.0"
authors = ["SixtyFPS <info@sixtyfps.io>"]
edition = "2021"
build = "build.rs"
# This is not meant to be used as a library from crate.io
publish = false
license = "(GPL-3.0-only OR LicenseRef-SixtyFPS-commercial)"
repository = "https://github.com/sixtyfpsui/sixtyfps"
homepage = "https://sixtyfps.io"


[lib]
path = "lib.rs"
crate-type = ["cdylib"]
name = "sixtyfps_node_native"

[dependencies]
once_cell = "1.5"
sixtyfps-compilerlib = { version = "=0.2.0", path="../../../sixtyfps_compiler" }
sixtyfps-interpreter = { version = "=0.2.0", path="../../../sixtyfps_runtime/interpreter",  features = ["display-diagnostics"] }
sixtyfps-corelib = { version = "=0.2.0", path="../../../sixtyfps_runtime/corelib" }
scoped-tls-hkt = "0.1"
neon = "0.8.0"
css-color-parser2 = "1.0.1"
spin_on = "0.1" #FIXME: remove and delegate to async JS instead
vtable = { version = "0.1.1", path="../../../helper_crates/vtable" }
generativity = "1"
rand = "0.8"

[build-dependencies]
neon-build = "0.8.0"
