# Copyright Â© SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: MIT OR Apache-2.0

[package]
name = "const-field-offset"
version = "0.1.3"
authors = ["Slint Developers <info@slint.dev>"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Wrapper around field-offset crate and const-field-offset-macro"
repository = "https://github.com/slint-ui/slint"
homepage = "https://slint.dev"

[features]
field-offset-trait = ["const-field-offset-macro/field-offset-trait"]

[dependencies]
const-field-offset-macro = { version = "=0.1.3", path = "./macro" }
field-offset = "0.3.2"

[dev-dependencies]
memoffset = "0.8.0"
