[book]
authors = ["Slint Developers <info@slint.dev>"]
language = "en"
multilingual = false
src = "src"
title = "Slint Memory Game QuickStart (Rust)"

[output.html]
theme = "../theme"

[output.linkcheck]  # enable the "mdbook-linkcheck" renderer
optional = true
