# Copyright Â© SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

name: Build and Test (Reusable)

on:
    workflow_call:
        inputs:
            os:
                description: 'Operating system to run on'
                required: true
                type: string
            rust_version:
                description: 'Rust version to use'
                required: true
                type: string
            cache_provider:
                description: 'Cache provider to use'
                required: false
                type: string
                default: "github"

jobs:
    build_and_test:
        env:
            DYLD_FRAMEWORK_PATH: /Users/runner/work/slint/Qt/6.2.2/macos/lib
            QT_QPA_PLATFORM: offscreen
            RUSTFLAGS: -D warnings
            CARGO_PROFILE_DEV_DEBUG: 0
            CARGO_INCREMENTAL: false
            RUST_BACKTRACE: 1
            SLINT_EMIT_DEBUG_INFO: 1

        runs-on: ${{ inputs.os }}

        steps:
            - uses: actions/checkout@v5
            - uses: ./.github/actions/install-linux-dependencies
            - uses: ./.github/actions/install-skia-dependencies
            - uses: ilammy/msvc-dev-cmd@v1
            - uses: actions/setup-python@v6
              with:
                python-version: '3.10'
            - name: Install Qt
              if: runner.os != 'Windows'
              uses: jurplel/install-qt-action@v4
              with:
                  version: "6.2.2"
                  setup-python: false
                  cache: true
            - name: Install ffmpeg and alsa (Linux)
              if: runner.os == 'Linux'
              run: sudo apt-get install clang libavcodec-dev libavformat-dev libavutil-dev libavfilter-dev libavdevice-dev libasound2-dev pkg-config
            - name: Install gstreamer and libunwind (Linux)
              if: runner.os == 'Linux'
              run: sudo apt-get install libunwind-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good
            - name: Setup headless display
              if: runner.os != 'macOS'
              uses: pyvista/setup-headless-display-action@v4
            - uses: ./.github/actions/setup-rust
              with:
                  toolchain: ${{ inputs.rust_version }}
                  key: x-v3
                  cache_provider: ${{ inputs.cache_provider }}
            - name: Run tests
              run:  cargo test --verbose --all-features --workspace --timings --exclude slint-node --exclude pyslint --exclude test-driver-node --exclude slint-node --exclude test-driver-nodejs --exclude test-driver-cpp --exclude mcu-board-support --exclude mcu-embassy --exclude printerdemo_mcu --exclude uefi-demo --exclude slint-cpp --exclude slint-python -- --skip=_qt::t
              env:
                  SLINT_CREATE_SCREENSHOTS: 1
              shell: bash
            - name: Run tests (qt)
              run: cargo test --verbose --all-features --workspace --exclude slint-node --exclude pyslint --exclude test-driver-node --exclude slint-node --exclude test-driver-nodejs --exclude test-driver-cpp --exclude mcu-board-support --exclude mcu-embassy --exclude printerdemo_mcu --exclude uefi-demo --exclude slint-cpp --exclude slint-python --bin test-driver-rust -- _qt --test-threads=1
              shell: bash
            - name: live-preview for rust test
              env:
                SLINT_LIVE_PREVIEW: 1
              run: cargo test --verbose --features=build-time,slint/live-preview -p test-driver-rust -- --skip=_qt::t
              shell: bash
            - name: Upload build timing report
              if: always()
              uses: actions/upload-artifact@v5
              with:
                  name: cargo-timings-${{ inputs.os }}-${{ inputs.rust_version }}
                  path: target/cargo-timings/cargo-timing.html
                  if-no-files-found: ignore
            - name: Archive screenshots after failed tests
              if: ${{ failure() }}
              uses: actions/upload-artifact@v5
              with:
                  name: screenshots-${{ inputs.os }}
                  path: |
                      tests/screenshots/references

