# Copyright Â© SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

# Run various formatters, linters, and type-checkers (Rust, C++, TypeScript, etc.)
name: Format, Lint, and type-check

on:
    workflow_call:
    workflow_dispatch:

jobs:
    format_lint_typecheck:
        runs-on: ubuntu-24.04
        env:
            CARGO_INCREMENTAL: false
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4.0.0
              with:
                version: 9.11.0
            - uses: actions/setup-node@v4
              with:
                node-version: 20
            - uses: ./.github/actions/install-linux-dependencies
            - uses: ./.github/actions/setup-rust
              with:
                  toolchain: nightly
                  components: rustfmt
                  target: aarch64-linux-android
            - name: Install wasm-pack
              run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh    
            - name: Setup Biome CLI
              uses: biomejs/setup-biome@v2                  
            - name: Rust format
              run: cargo fmt --
            - name: C++ format
              run: find -iname \*.h -o -iname \*.cpp | xargs clang-format -i
            - name: Run biome for top-level json config itself
              run: biome format biome.json
            - name: Format, Lint on npm projects
              run: |
                  pnpm install --frozen-lockfile
                  pnpm format
                  pnpm lint
            - name: Suggest format changes
              uses: reviewdog/action-suggester@v1
              with:
                  tool_name: formatters
                  level: error
                  fail_on_error: true
            - name: Build Node.js API before type-check
              working-directory: api/node
              run: pnpm build:debug
            - name: Build wasm-interpreter before type check
              working-directory: tools/slintpad
              run: pnpm build:wasm_interpreter
            - name: Build wasm-lsp before type check
              working-directory: editors/vscode
              run: pnpm build:wasm_lsp
            - name: Typecheck on npm projects
              run: |
                  pnpm type-check
