# Copyright Â© SixtyFPS GmbH <info@slint-ui.com>
# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

[package]
name = "i-slint-parser-test-macro"
version = "1.0.3"
authors = ["Slint Developers <info@slint-ui.com>"]
edition = "2021"
publish = false
license = "GPL-3.0-only OR LicenseRef-Slint-commercial"

[lib]
proc-macro = true
path = "lib.rs"

[dependencies]
quote = "1.0"
